import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useLocation,useNavigate} from 'react-router-dom';
import {LayoutDashboard,MessageSquare,Package,CircleHelp,ShoppingCart,Zap,Users,LogOut,Plus,Search,Settings as SettingsIcon,CreditCard,Phone,RefreshCw,Trash2,Send,ShieldCheck,Database,Activity,FileText,Globe,HandCoins,Bell} from 'lucide-react';
import {io} from 'socket.io-client';
import './styles.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:5050';
const api=async(path,opts={})=>{const t=localStorage.getItem('token');let r;try{r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(t?{Authorization:`Bearer ${t}`}:{}) ,...(opts.headers||{})}})}catch{throw new Error('Cannot connect to the API. Please try again shortly.')}if(r.status===401&&t){localStorage.removeItem('token');location.reload();throw new Error('Your session expired. Please sign in again.')}if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`HTTP ${r.status}`);return r.status===204?null:r.json();};

function App(){
 const [me,setMe]=useState(null),[loading,setLoading]=useState(true); const nav=useNavigate(); const loc=useLocation();
 useEffect(()=>{api('/auth/me').then(setMe).catch(()=>setMe(null)).finally(()=>setLoading(false));},[]);
 if(loading)return <div className="center">Loading...</div>;
 if(!me)return <Login onLogin={u=>{setMe(u);nav(u.role==='SUPERADMIN'?'/admin':'/');}}/>;
 if(me.role==='SUPERADMIN')return <Admin me={me} logout={()=>{localStorage.clear();setMe(null)}}/>;
 return <Portal me={me} logout={()=>{localStorage.clear();setMe(null)}}/>;
}

function Login({onLogin}){const [email,setEmail]=useState('owner@example.com'),[password,setPassword]=useState('Admin@123456'),[error,setError]=useState('');async function go(e){e.preventDefault();setError('');try{const x=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('token',x.token);onLogin(x.user);}catch(e){setError(e.message)}}return <div className="login-page"><form className="login-card" onSubmit={go}><div className="brand big"><span className="logo-grid">✦</span>AgentStart</div><h1>Sign in</h1><p>Manage your WhatsApp sales agent.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className="primary">Sign In</button>{error&&<div className="error">{error}</div>}<small>Demo owner: owner@example.com / Admin@123456<br/>Superadmin: admin@example.com / Admin@123456</small></form></div>}

const items=[['/','Dashboard',LayoutDashboard],['/chats','Chats',MessageSquare],['/products','Products',Package],['/faqs','FAQs',CircleHelp],['/orders','Orders',ShoppingCart],['/integrations','Integrations',Zap],['/account','Account',Users]];
function Portal({me,logout}){const loc=useLocation();const nav=useNavigate();const page=loc.pathname;return <div className="shell"><aside><div className="brand"><span className="logo-grid">✦</span>AgentStart</div><nav>{items.map(([p,n,I])=><button key={p} onClick={()=>nav(p)} className={page===p?'active':''}><I size={20}/>{n}</button>)}</nav><div className="aside-bottom"><button onClick={logout}><LogOut size={20}/>Sign Out</button><div className="powered">Powered by <b>AgentStart</b></div></div></aside><main>{page==='/'?<Dashboard/>:page==='/chats'?<Chats/>:page==='/products'?<Products/>:page==='/faqs'?<Faqs/>:page==='/orders'?<Orders/>:page==='/integrations'?<Integrations/>:<Account me={me}/>}</main><div className="ai-fab">✦</div></div>}

function Header({title,sub,action}){return <div className="page-head"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Stat({label,value,icon:Icon}){return <div className="stat"><div><span>{label}</span><strong>{value}</strong></div>{Icon&&<Icon size={22}/>}</div>}

function Dashboard(){const [d,setD]=useState({});useEffect(()=>{api('/dashboard').then(setD)},[]);return <><Header title="Dashboard" sub="Overview of your WhatsApp agent"/><div className="stats three"><Stat label="Total Orders" value={d.totalOrders||0} icon={ShoppingCart}/><Stat label="Total Conversations" value={d.totalConversations||0} icon={MessageSquare}/><Stat label="Total Revenue" value={`LKR ${(d.totalRevenue||0).toLocaleString()}`} icon={Activity}/></div><div className="quick-grid">{[['Connect WhatsApp',Phone],['Add Order',ShoppingCart],['Add Product',Package],['Add FAQ',CircleHelp],['Change Language',Globe],['Send Invoices',FileText],['Follow-up Messages',RefreshCw],['Notifications Setup',Bell],['Collect Fields',Database],['View Chats',MessageSquare]].map(([x,I])=><div className="quick" key={x}><I size={20}/>{x}</div>)}</div><div className="promo"><ShoppingCart size={52}/><div><h2>Orders Dashboard</h2><p>Track orders, payments, delivery status and revenue.</p><small>Visit Orders to see customer orders and update status from pending to delivered.</small></div><button>Go →</button></div></>}

function Products(){const [rows,setRows]=useState([]),[open,setOpen]=useState(false);const [f,setF]=useState({name:'',sku:'',category:'',price:'',stock:''});const load=()=>api('/products').then(setRows);useEffect(()=>{load()},[]);async function save(e){e.preventDefault();await api('/products',{method:'POST',body:JSON.stringify(f)});setOpen(false);setF({name:'',sku:'',category:'',price:'',stock:''});load()}return <><Header title="Products" sub="Manage your product catalog for the chatbot" action={<button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>Add Product</button>}/><div className="stats four"><Stat label="Total Products" value={rows.length}/><Stat label="Available" value={rows.filter(x=>x.stock>0).length}/><Stat label="Categories" value={new Set(rows.map(x=>x.category).filter(Boolean)).size}/><Stat label="Avg. Price" value={`LKR ${rows.length?(rows.reduce((s,x)=>s+Number(x.price),0)/rows.length).toFixed(0):0}`}/></div><Panel title="Product Catalog">{rows.length?<table><thead><tr><th>Name</th><th>SKU</th><th>Category</th><th>Price</th><th>Stock</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.sku||'-'}</td><td>{x.category||'-'}</td><td>LKR {Number(x.price).toFixed(2)}</td><td>{x.stock}</td><td><button className="icon danger" onClick={async()=>{await api('/products/'+x.id,{method:'DELETE'});load()}}><Trash2 size={16}/></button></td></tr>)}</tbody></table>:<Empty icon={Package} title="No products yet" text="Add your first product using the button above."/>}</Panel>{open&&<Modal title="Add Product" close={()=>setOpen(false)}><form onSubmit={save} className="form-grid"><input required placeholder="Product name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="SKU" value={f.sku} onChange={e=>setF({...f,sku:e.target.value})}/><input placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/><input required type="number" step="0.01" placeholder="Price" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/><input required type="number" placeholder="Stock" value={f.stock} onChange={e=>setF({...f,stock:e.target.value})}/><button className="primary">Save Product</button></form></Modal>}</>}

function Faqs(){const [rows,setRows]=useState([]),[open,setOpen]=useState(false),[f,setF]=useState({question:'',answer:''});const load=()=>api('/faqs').then(setRows);useEffect(() => { load(); },[]);async function save(e){e.preventDefault();await api('/faqs',{method:'POST',body:JSON.stringify(f)});setOpen(false);setF({question:'',answer:''});load()}return <><Header title="FAQs" sub="Manage FAQs for the chatbot" action={<button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>Add FAQ</button>}/><Panel title={`FAQ List · ${rows.length} configured`}>{rows.length?<table><thead><tr><th>Question</th><th>Answer</th><th>Status</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.question}</td><td>{x.answer}</td><td><span className="pill">Active</span></td><td><button className="icon danger" onClick={async()=>{await api('/faqs/'+x.id,{method:'DELETE'});load()}}><Trash2 size={16}/></button></td></tr>)}</tbody></table>:<Empty icon={CircleHelp} title="No FAQs configured yet" text="Add your first FAQ to help your chatbot answer common questions."/>}</Panel>{open&&<Modal title="Add FAQ" close={()=>setOpen(false)}><form onSubmit={save} className="form-grid"><input required placeholder="Question" value={f.question} onChange={e=>setF({...f,question:e.target.value})}/><textarea required placeholder="Answer" value={f.answer} onChange={e=>setF({...f,answer:e.target.value})}/><button className="primary">Save FAQ</button></form></Modal>}</>}

function Orders(){const [rows,setRows]=useState([]);const load=()=>api('/orders').then(setRows);useEffect(() => { load(); },[]);const delivered=rows.filter(x=>x.status==='DELIVERED');return <><Header title="Orders" sub="Manage customer orders from your chatbot"/><div className="stats five"><Stat label="Total" value={rows.length}/><Stat label="Pending" value={rows.filter(x=>x.status==='PENDING').length}/><Stat label="Active" value={rows.filter(x=>!['DELIVERED','CANCELLED'].includes(x.status)).length}/><Stat label="Delivered" value={delivered.length}/><Stat label="Revenue" value={`LKR ${delivered.reduce((s,x)=>s+Number(x.total),0).toFixed(0)}`}/></div><Panel>{rows.length?<table><thead><tr><th>Customer</th><th>Phone</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.customerName}</td><td>{x.customerPhone}</td><td>LKR {Number(x.total).toFixed(2)}</td><td><select value={x.status} onChange={async e=>{await api('/orders/'+x.id+'/status',{method:'PATCH',body:JSON.stringify({status:e.target.value})});load()}}>{['PENDING','CONFIRMED','PREPARING','SHIPPED','DELIVERED','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></td><td>{new Date(x.createdAt).toLocaleString()}</td></tr>)}</tbody></table>:<Empty icon={ShoppingCart} title="No orders" text="Orders collected by your agent will appear here."/>}</Panel></>}

function Chats(){const [cs,setCs]=useState([]),[selected,setSelected]=useState(null),[msgs,setMsgs]=useState([]),[text,setText]=useState('');const load=()=>api('/conversations').then(setCs);useEffect(()=>{load();const s=io(API,{auth:{token:localStorage.getItem('token')}});s.on('message',()=>{load(); if(selected)api('/conversations/'+selected.id+'/messages').then(setMsgs)});return()=>s.close()},[selected?.id]);async function choose(c){setSelected(c);setMsgs(await api('/conversations/'+c.id+'/messages'))}async function send(e){e.preventDefault();if(!text.trim())return;await api('/conversations/'+selected.id+'/send',{method:'POST',body:JSON.stringify({body:text})});setText('');setMsgs(await api('/conversations/'+selected.id+'/messages'))}return <><Header title="Conversations" sub="WhatsApp chat history and live messages"/><div className="chat-layout"><div className="chat-list"><div className="search"><Search size={18}/><input placeholder="Search chats..."/></div>{cs.map(c=><button key={c.id} onClick={()=>choose(c)} className={selected?.id===c.id?'chosen':''}><b>{c.customerName||c.phone}</b><span>{c.phone}</span><small>{c.messages?.[0]?.body||'No messages'}</small></button>)}</div><div className="chat-main">{selected?<><div className="chat-top"><div><b>{selected.customerName||selected.phone}</b><span>{selected.phone}</span></div><button onClick={async()=>{await api('/conversations/'+selected.id+'/handoff',{method:'PATCH',body:JSON.stringify({humanHandoff:!selected.humanHandoff})});load()}}>Human handoff</button></div><div className="messages">{msgs.map(m=><div className={'bubble '+(m.direction==='out'?'out':'in')} key={m.id}>{m.body}<small>{new Date(m.createdAt).toLocaleTimeString()}</small></div>)}</div><form className="composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type a reply..."/><button className="primary"><Send size={18}/></button></form></>:<Empty icon={MessageSquare} title="Select a conversation" text="Choose a chat from the list to view messages"/>}</div></div></>}

function Integrations(){const cards=[['WooCommerce','woo'],['Shopify','shop'],['Stripe','stripe'],['WhatsApp Cloud API','wa'],['Custom Business API','api']];return <><Header title="Integrations" sub="Connect services to enhance your bot"/><div className="integration-grid">{cards.map(([n])=><div className="integration" key={n}><Zap size={26}/><b>{n}</b><span>Configure</span></div>)}</div><Panel title="Production API integration"><p>Use the custom API integration for live product price, stock, delivery details, and order creation. The agent is instructed never to invent live commerce data.</p><p><b>Recommended:</b> connect your business API with server-side credentials and expose only the endpoints the agent needs.</p></Panel></>}

function Account({me}){const [tab,setTab]=useState('whatsapp');return <><Header title="Account" sub="Manage your account, billing, and integrations"/><div className="tabs">{[['whatsapp',Phone,'WhatsApp'],['billing',CreditCard,'Billing'],['settings',SettingsIcon,'Settings']].map(([id,I,n])=><button className={tab===id?'on':''} key={id} onClick={()=>setTab(id)}><I size={18}/>{n}</button>)}</div>{tab==='whatsapp'?<WhatsAppSettings/>:tab==='billing'?<Billing/>:<BotSettings me={me}/>}</>}

function WhatsAppSettings(){const [rows,setRows]=useState([]),[name,setName]=useState('My Business WhatsApp'),[qr,setQr]=useState(null);const load=()=>api('/whatsapp/sessions').then(setRows);useEffect(() => { load(); },[]);async function add(){await api('/whatsapp/sessions',{method:'POST',body:JSON.stringify({name,mode:'QR'})});load()}async function connect(s){await api('/whatsapp/sessions/'+s.id+'/connect',{method:'POST'});const poll=setInterval(async()=>{const x=await api('/whatsapp/sessions/'+s.id+'/qr');if(x.qr)setQr({id:s.id,data:x.qr});if(x.status==='connected'){clearInterval(poll);setQr(null);load()}},1500);setTimeout(()=>clearInterval(poll),120000)}return <><h2>WhatsApp</h2><p className="muted">Connect your bot to WhatsApp to handle customer messages automatically.</p><Panel title="Connect WhatsApp"><div className="inline"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Session name"/><button className="primary" onClick={add}>Create Session</button></div>{rows.map(s=><div className="session" key={s.id}><div><Phone/><div><b>{s.name}</b><span>{s.phone||s.status}</span></div></div><div className="inline"><span className={'pill '+(s.status==='connected'?'green':'')}>{s.status}</span>{s.status!=='connected'&&<button className="primary" onClick={()=>connect(s)}>Generate QR Code</button>}<button className="danger-btn" onClick={async()=>{await api('/whatsapp/sessions/'+s.id,{method:'DELETE'});load()}}><Trash2 size={16}/></button></div></div>)}{qr&&<div className="qr-box"><h3>Scan with WhatsApp → Linked devices</h3><img src={qr.data}/><p>Keep this page open until the session becomes connected.</p></div>}</Panel><div className="notice"><ShieldCheck/><div><b>Production note</b><p>QR linking uses a WhatsApp Web session. For larger commercial deployments, use the official Meta WhatsApp Cloud API integration.</p></div></div></>}

function Billing(){const [b,setB]=useState(null);useEffect(()=>{api('/billing').then(setB)},[]);if(!b)return <div>Loading...</div>;return <><h2>Billing</h2><p className="muted">Manage your subscription and usage</p><div className="billing-card"><div><b>{b.plan}</b><span className="pill green">Current Plan</span></div><div className="usage"><div><span>Customer Conversations</span><strong>{b.conversationUsage} / {b.conversationLimit}</strong></div><div><span>AI Actions</span><strong>{b.aiActionUsage} / {b.aiActionLimit}</strong></div><div><span>Next billing</span><strong>{b.nextBilling}</strong></div></div></div><h2>Top-ups</h2><div className="topup"><MessageSquare/><b>Extra conversations</b><span>+1000 conversations</span><strong>Rs. 2,000</strong><button>Buy Now</button></div></>}

function BotSettings({me}){const [s,setS]=useState(null),[msg,setMsg]=useState('');useEffect(()=>{api('/settings').then(setS)},[]);if(!s)return <div>Loading...</div>;const bi=s.businessInfo||{};const rules=bi.rules||[];async function save(){await api('/settings',{method:'PUT',body:JSON.stringify(s)});setMsg('Saved');setTimeout(()=>setMsg(''),1500)}return <><h2>Settings</h2><p className="muted">Configure your chatbot behavior</p><Panel title="Capabilities"><div className="chips">{['api_integration','order_collection','multilingual_support','human_handoff'].map(x=><span className="chip" key={x}>{x}</span>)}</div></Panel><Panel title="Business Info"><div className="form-grid two"><label>Hours<input value={bi.hours||''} onChange={e=>setS({...s,businessInfo:{...bi,hours:e.target.value}})}/></label><label>Contact<input value={bi.contact||''} onChange={e=>setS({...s,businessInfo:{...bi,contact:e.target.value}})}/></label></div><h4>Rules & Guidelines</h4>{rules.map((r,i)=><div className="rule" key={i}>— {r}</div>)}</Panel><Panel title="Default Language"><select value={s.defaultLanguage} onChange={e=>setS({...s,defaultLanguage:e.target.value})}><option value="auto">Auto-detect (match user's language)</option><option value="en">English</option><option value="si">Sinhala</option></select></Panel><Panel title="Welcome Sequence"><textarea value={s.welcomeSequence?.[0]?.content||''} onChange={e=>setS({...s,welcomeSequence:[{type:'text',content:e.target.value}]})}/></Panel><Panel title="Payment Methods"><p>No payment methods configured</p><button className="secondary"><Plus size={16}/> Add</button></Panel><Panel title="Document Templates"><p>Create PDF templates your agent can generate (invoices, quotations, receipts).</p><button className="secondary"><Plus size={16}/> New Template</button></Panel><Panel title="Information Collection"><p>Configure what information your agent collects from customers during conversations.</p><button className="secondary"><Plus size={16}/> Add Field</button></Panel><Panel title="System Prompt"><textarea className="prompt" value={s.systemPrompt||''} onChange={e=>setS({...s,systemPrompt:e.target.value})}/></Panel><Panel title="Profile"><div className="form-grid two"><label>Email<input value={me.email} disabled/></label><label>Display Name<input value={me.displayName||''} disabled/></label></div></Panel><button className="primary" onClick={save}>Save Settings</button>{msg&&<span className="saved">{msg}</span>}<div className="danger-zone"><h3>Danger Zone</h3><p>Reconfigure Bot deletes products, services, FAQs, welcome sequence, payment methods, templates, and settings. Chat history and billing stats are preserved.</p><button className="danger-btn" onClick={async()=>{if(confirm('Reconfigure this bot?')){await api('/settings/reconfigure',{method:'POST'});location.reload()}}}>Reconfigure</button></div></>}

function Admin({logout}){const [o,setO]=useState({}),[ws,setWs]=useState([]),[open,setOpen]=useState(false),[tab,setTab]=useState('overview'),[f,setF]=useState({name:'',slug:'',email:'',password:'Admin@123456'});const load=()=>{api('/admin/overview').then(setO);api('/admin/workspaces').then(setWs)};useEffect(() => { load(); },[]);async function save(e){e.preventDefault();await api('/admin/workspaces',{method:'POST',body:JSON.stringify(f)});setOpen(false);load()};const pageTitle={overview:'Super Admin',tenants:'Tenants',plans:'Plans',system:'System'}[tab];const pageSub={overview:'Manage tenants, usage, plans, and platform health',tenants:'Manage customer workspaces and owners',plans:'Manage subscription plans and limits',system:'Monitor platform health and services'}[tab];return <div className="admin-shell"><aside><div className="brand"><span className="logo-grid">✦</span>AgentStart Admin</div><nav>{[['overview','Overview',LayoutDashboard],['tenants','Tenants',Users],['plans','Plans',CreditCard],['system','System',Activity]].map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon size={20}/>{label}</button>)}</nav><div className="aside-bottom"><button onClick={logout}><LogOut size={20}/>Sign Out</button></div></aside><main><Header title={pageTitle} sub={pageSub} action={<button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>Create Tenant</button>}/><div className="stats four"><Stat label="Tenants" value={o.workspaces||0}/><Stat label="Users" value={o.users||0}/><Stat label="Orders" value={o.orders||0}/><Stat label="Conversations" value={o.conversations||0}/></div><Panel title={tab==='overview'?'Platform Overview':tab==='tenants'?'Customer Workspaces':tab==='plans'?'Subscription Plans':'System Health'}><table><thead><tr><th>Business</th><th>Owner</th><th>Products</th><th>Orders</th><th>Chats</th><th>Plan</th></tr></thead><tbody>{ws.map(w=><tr key={w.id}><td><b>{w.name}</b><br/><small>{w.slug}</small></td><td>{w.users?.[0]?.email||'-'}</td><td>{w._count.products}</td><td>{w._count.orders}</td><td>{w._count.conversations}</td><td><span className="pill green">{w.plan}</span></td></tr>)}</tbody></table></Panel>{tab!=='overview'&&<AdminConfig tab={tab}/>}{open&&<Modal title="Create Tenant" close={()=>setOpen(false)}><form className="form-grid" onSubmit={save}><input required placeholder="Business name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="Slug" value={f.slug} onChange={e=>setF({...f,slug:e.target.value})}/><input required type="email" placeholder="Owner email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input required placeholder="Temporary password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><button className="primary">Create</button></form></Modal>}</main></div>}

function AiProviderConfig({config:c,setConfig:setC,save,msg}){return <Panel title="AI Provider Configuration"><div className="form-grid"><label>Provider<input value={c.ai.provider} onChange={e=>setC({...c,ai:{...c.ai,provider:e.target.value}})}/></label><label>Model<input value={c.ai.model} onChange={e=>setC({...c,ai:{...c.ai,model:e.target.value}})}/></label><label>Base URL (optional)<input placeholder="https://openrouter.ai/api/v1" value={c.ai.baseURL||''} onChange={e=>setC({...c,ai:{...c.ai,baseURL:e.target.value}})}/></label><label>API key<input type="password" placeholder="Paste provider API key" value={c.ai.apiKey||''} onChange={e=>setC({...c,ai:{...c.ai,apiKey:e.target.value,apiKeyConfigured:Boolean(e.target.value)}})}/></label></div><button className="primary" onClick={save}>Save AI Settings</button>{msg&&<span className="saved">{msg}</span>}</Panel>}
function AdminConfig({tab}){const [c,setC]=useState(null),[health,setHealth]=useState(null),[msg,setMsg]=useState('');useEffect(()=>{api('/admin/config').then(setC);if(tab==='system')api('/admin/health').then(setHealth)},[tab]);if(!c)return <Panel title="Loading configuration">Loading...</Panel>;async function save(){await api('/admin/config',{method:'PUT',body:JSON.stringify(c)});setMsg('Saved');setTimeout(()=>setMsg(''),1500)}if(tab==='plans')return <Panel title="Plans & Pricing"><div className="form-grid">{c.plans.map((p,i)=><div className="panel" key={p.key}><b>{p.name} ({p.key})</b><input value={p.monthlyPrice} type="number" placeholder="Monthly price" onChange={e=>{const plans=[...c.plans];plans[i]={...p,monthlyPrice:Number(e.target.value)};setC({...c,plans})}}/><input value={p.conversationLimit} type="number" placeholder="Conversation limit" onChange={e=>{const plans=[...c.plans];plans[i]={...p,conversationLimit:Number(e.target.value)};setC({...c,plans})}}/><input value={p.aiActionLimit} type="number" placeholder="AI action limit" onChange={e=>{const plans=[...c.plans];plans[i]={...p,aiActionLimit:Number(e.target.value)};setC({...c,plans})}}/></div>)}</div><button className="primary" onClick={save}>Save Plans</button>{msg&&<span className="saved">{msg}</span>}</Panel>;if(tab==='system')return <><Panel title="Platform Health"><p>API: <b>{health?.api||'Loading'}</b></p><p>Database: <b>{health?.database||'Loading'}</b></p><p>OpenAI configured: <b>{health?.openai?'Yes':'No'}</b></p><p>Connected WhatsApp sessions: <b>{health?.whatsappSessions??'Loading'}</b></p></Panel><AiProviderConfig config={c} setConfig={setC} save={save} msg={msg}/></>;return <AiProviderConfig config={c} setConfig={setC} save={save} msg={msg}/>}
function Panel({title,children}){return <section className="panel">{title&&<h3>{title}</h3>}{children}</section>}
function Empty({icon:Icon,title,text}){return <div className="empty"><Icon size={50}/><h3>{title}</h3><p>{text}</p></div>}
function Modal({title,close,children}){return <div className="modal-back"><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
